---
apiVersion: metrifuge.com/v1alpha1
kind: Exporter
metadata:
  name: mf-log-exporter
  namespace: metrifuge
  labels:
    app: metrifuge
    exporter-type: log
spec:
  type: Log
  refreshInterval: 10s
  logSource:
    name: mf-logsource
    namespace: metrifuge
  destination:
    type: honeycomb
    honeycomb:
      # TODO: Replace with your actual Honeycomb API key
      apiKey: "YOUR_HONEYCOMB_API_KEY"
      dataset: "metrifuge-logs"
      # Optional: Specify environment for better data organization
      environment: "development"

---
apiVersion: metrifuge.com/v1alpha1
kind: Exporter
metadata:
  name: mf-metric-exporter
  namespace: metrifuge
  labels:
    app: metrifuge
    exporter-type: metric
spec:
  type: Metric
  refreshInterval: 30s
  logSource:
    name: mf-logsource
    namespace: metrifuge
  destination:
    type: honeycomb
    honeycomb:
      # TODO: Replace with your actual Honeycomb API key
      apiKey: "YOUR_HONEYCOMB_API_KEY"
      dataset: "metrifuge-metrics"
      # Optional: Specify environment for better data organization
      environment: "development"
