apiVersion: metrifuge.com/v1alpha1
kind: RuleSet
metadata:
  name: metrifuge-debug-logs
  namespace: metrifuge
spec:
  selector:
    matchLabels:
      app: metrifuge
  rules:
    - name: parse_debug_logs
      description: Parse debug level logs from metrifuge application
      pattern: 'time="%{TIMESTAMP_ISO8601:timestamp}"\s+level=%{WORD:log_level}\s+msg="%{GREEDYDATA:message}"(?:\s+func=%{GREEDYDATA:function})?(?:\s+file="%{GREEDYDATA:source_file}")?'
      action: analyze
      createMetrics: true
      metrics:
        - name: metrifuge_debug_logs_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: log_level
              value:
                type: String
                manualValue: "debug"
              type: String
            - key: component
              value:
                type: String
                manualValue: "metrifuge"
              type: String
        - name: metrifuge_warn_logs_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: log_level
              value:
                type: String
                manualValue: "warn"
              type: String
            - key: component
              value:
                type: String
                manualValue: "metrifuge"
              type: String
    
    - name: detect_crd_validation
      description: Detect CRD validation debug messages
      pattern: 'time="%{TIMESTAMP_ISO8601:timestamp}"\s+level=debug\s+msg="\s*%{WORD:field_name}:\s*%{GREEDYDATA:field_value}"'
      action: conditional
      createMetrics: true
      conditional:
        field1:
          type: String
          grokKey: field_name
        operator: Equals
        field2:
          type: String
          manualValue: "Name"
        actionTrue: "process_crd_validation"
        actionFalse: "continue"
        metricsTrue:
          - name: metrifuge_crd_validation_name_field_total
            kind: Int64Counter
            value:
              type: Int64
              manualValue: "1"
            attributes:
              - key: field
                value:
                  type: String
                  manualValue: "Name"
                type: String
              - key: condition_result
                value:
                  type: String
                  manualValue: "true"
                type: String
        metricsFalse:
          - name: metrifuge_crd_validation_other_field_total
            kind: Int64Counter
            value:
              type: Int64
              manualValue: "1"
            attributes:
              - key: field
                value:
                  type: String
                  grokKey: "field_name"
                type: String
              - key: condition_result
                value:
                  type: String
                  manualValue: "false"
                type: String
      metrics:
        - name: metrifuge_crd_validation_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: field
              value:
                type: String
                manualValue: "Name"
              type: String
    
    - name: log_level_distribution
      description: Track distribution of log levels
      pattern: 'time="%{TIMESTAMP_ISO8601:timestamp}"\s+level=%{WORD:log_level}'
      action: discard
      createMetrics: false

    - name: function_call_tracker
      description: Track function calls with dynamic attributes from grok captures
      pattern: 'time="%{TIMESTAMP_ISO8601:timestamp}"\s+level=%{WORD:log_level}\s+msg="%{GREEDYDATA:message}"\s+func=%{DATA:function}\s+file="%{DATA:source_file}"'
      action: analyze
      createMetrics: true
      metrics:
        - name: metrifuge_function_calls_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: function_name
              value:
                type: String
                grokKey: "function"
              type: String
            - key: source_file
              value:
                type: String
                grokKey: "source_file"
              type: String
            - key: log_level
              value:
                type: String
                grokKey: "log_level"
              type: String