apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crd-reader-binding
subjects:
- kind: ServiceAccount
  name: metrifuge-sa
  namespace: metrifuge
roleRef:
  kind: ClusterRole
  name: crd-reader-role
  apiGroup: rbac.authorization.k8s.io
