apiVersion: metrifuge.com/v1alpha1
kind: RuleSet
metadata:
  name: uuid-parser-ruleset
  labels:
    app: uuid-parser
spec:
  selector:
    matchLabels:
      app: metrifuge
  rules:
    - name: parse-uuid-log
      description: Parse UUID and date information from test log messages
      pattern: '\[%{DAY:day} %{MONTH:month} %{MONTHDAY:monthday} %{TIME:time} %{TZ:timezone} %{YEAR:year}\] Hello World! This is a test log message, random UUID: %{DATA:uuid_part1}-%{DATA:uuid_part2}-%{DATA:uuid_part3}-%{DATA:uuid_part4}-%{GREEDYDATA:uuid_part5}'
      action: conditional
      conditional:
        field1:
          type: String
          grokKey: "uuid_part1"
        operator: Equals
        field2:
          type: String
          manualValue: "0000"
        actionTrue: forward
        actionFalse: forward
        metricsTrue:
          - name: uuid_0000_check
            kind: Int64Counter
            value:
              type: Int64
              manualValue: "1"
        metricsFalse:
          - name: uuid_0000_check
            kind: Int64Counter
            value:
              type: Int64
              manualValue: "-1"
      createMetrics: true
      metrics:
        - name: uuid_logs_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: day
              value:
                type: String
                grokKey: "day"
              type: String
            - key: month
              value:
                type: String
                grokKey: "month"
              type: String
            - key: monthday
              value:
                type: String
                grokKey: "monthday"
              type: String
            - key: time
              value:
                type: String
                grokKey: "time"
              type: String
            - key: timezone
              value:
                type: String
                grokKey: "timezone"
              type: String
            - key: year
              value:
                type: String
                grokKey: "year"
              type: String
            - key: uuid_segment_1
              value:
                type: String
                grokKey: "uuid_part1"
              type: String
            - key: uuid_segment_2
              value:
                type: String
                grokKey: "uuid_part2"
              type: String
            - key: uuid_segment_3
              value:
                type: String
                grokKey: "uuid_part3"
              type: String
            - key: uuid_segment_4
              value:
                type: String
                grokKey: "uuid_part4"
              type: String
            - key: uuid_segment_5
              value:
                type: String
                grokKey: "uuid_part5"
              type: String
