apiVersion: metrifuge.com/v1alpha1
kind: RuleSet
metadata:
  name: uuid-parser-ruleset
  labels:
    app: uuid-parser
spec:
  selector:
    matchLabels:
      app: metrifuge
  rules:
    - name: parse-uuid-log
      description: Parse UUID and date information from test log messages
      pattern: '\[%{DAY:day} %{MONTH:month} %{MONTHDAY:monthday} %{TIME:time} %{TZ:timezone} %{YEAR:year}\] Hello World! This is a test log message, random UUID: %{UUID:uuid_full}'
      action: analyze
      createMetrics: true
      metrics:
        - name: uuid_logs_total
          kind: Int64Counter
          value:
            type: Int64
            manualValue: "1"
          attributes:
            - key: day
              value:
                type: String
                grokKey: "day"
              type: String
            - key: month
              value:
                type: String
                grokKey: "month"
              type: String
            - key: monthday
              value:
                type: String
                grokKey: "monthday"
              type: String
            - key: time
              value:
                type: String
                grokKey: "time"
              type: String
            - key: timezone
              value:
                type: String
                grokKey: "timezone"
              type: String
            - key: year
              value:
                type: String
                grokKey: "year"
              type: String
            - key: uuid_full
              value:
                type: String
                grokKey: "uuid_full"
              type: String
